#!/bin/bash
yellow='\e[1;33m'
white='\e[1;37m'
lightblue='\e[1;34m'
lightgreen='\e[1;32m'
lightpurple='\e[1;35m'
stopcolor='\e[m'
rm -f config.tes
SERVER=$1
WORKER=$2
WALLET=$3
if [ -z $WALLET ]; then
  echo -e $white" ----------------------------------------------------------"
  echo -e $lightgreen" Script usage:"
  echo -e $lightblue" $0 <Server:Port> <Worker ID> <Your XMR Wallet>"
  echo -e $white" ----------------------------------------------------------"
  exit 1
fi
echo "{
    \"api\": {
        \"id\": null,
        \"worker-id\": null
    },
    \"http\": {
        \"enabled\": false,
        \"host\": \"127.0.0.1\",
        \"port\": 0,
        \"access-token\": null,
        \"restricted\": true
    },
    \"autosave\": true,
    \"background\": false,
    \"colors\": true,
    \"randomx\": {
        \"init\": -1,
        \"mode\": \"auto\",
        \"1gb-pages\": false,
        \"rdmsr\": true,
        \"wrmsr\": true,
        \"numa\": true
    },
    \"cpu\": {
        \"enabled\": true,
        \"huge-pages\": true,
        \"hw-aes\": null,
        \"priority\": null,
        \"memory-pool\": false,
        \"yield\": true,
        \"max-threads-hint\": 100,
        \"asm\": true,
        \"argon2-impl\": null,
        \"astrobwt-max-size\": 550,
        \"cn/0\": false,
        \"cn-lite/0\": false
    },
    \"opencl\": {
        \"enabled\": false,
        \"cache\": true,
        \"loader\": null,
        \"platform\": \"AMD\",
        \"adl\": true,
        \"cn/0\": false,
        \"cn-lite/0\": false
    },
    \"cuda\": {
        \"enabled\": false,
        \"loader\": null,
        \"nvml\": true,
        \"cn/0\": false,
        \"cn-lite/0\": false
    },
    \"donate-level\": 1,
    \"donate-over-proxy\": 1,
    \"log-file\": \"logs\",
    \"pools\": [
        {
            \"algo\": null,
            \"coin\": null,
	    \"url\": \"$SERVER\",
            \"user\": \"$WALLET\",
            \"pass\": \"$WORKER\",
            \"rig-id\": null,
            \"nicehash\": false,
            \"keepalive\": false,
            \"enabled\": true,
            \"tls\": false,
            \"tls-fingerprint\": null,
            \"daemon\": false,
            \"socks5\": null,
            \"self-select\": null
        }
    ],
    \"print-time\": 60,
    \"health-print-time\": 60,
    \"retries\": 5,
    \"retry-pause\": 5,
    \"syslog\": false,
    \"tls\": {
        \"enabled\": false,
        \"protocols\": null,
        \"cert\": null,
        \"cert_key\": null,
        \"ciphers\": null,
        \"ciphersuites\": null,
        \"dhparam\": null
    },
    \"user-agent\": null,
    \"verbose\": 0,
    \"watch\": true
}" > config.json
echo -e $white
echo -e " config.json has been created! "
echo -e $stopcolor
echo -e " Server     :"$lightblue $SERVER $stopcolor
echo -e " XMR Wallet :"$yellow $WALLET $stopcolor
echo -e " Worker ID  :"$lightpurple $WORKER $stopcolor
echo -e $stopcolor
